Repository v8/v8.dev, pull requests merged in 2018-10, with the labels that each got.

#7 Use templatedUrls for /
  workbox-config.js
Labels: cla: yes

#10 Optimize `twitter.svg`
  src/_img/twitter.svg
Labels: cla: yes

#11 Fixed 231 -> 2^31 (SMI size on 32-bit systems)
  src/blog/hash-code.md
Labels: cla: no

#12 Further losslessly optimize images
  src/_img/10-years/v8-bench@2x.png
  src/_img/background-compilation/bytecode.png
  src/_img/background-compilation/desktop.png
  src/_img/concurrent-marking/12.png
  src/_img/csa/csa.png
  src/_img/docs/trace/runtime-stats.png
  src/_img/embedded-builtins/code-off-heap.png
  src/_img/embedded-builtins/code-on-heap.png
  src/_img/embedded-builtins/results.png
  src/_img/fast-for-in/enum-cache.png
  src/_img/fast-for-in/facebook.png
  src/_img/fast-for-in/fastkeyaccumulator.png
  src/_img/fast-properties/adding-properties.png
  src/_img/fast-properties/fast-vs-slow-properties.png
  src/_img/fast-properties/hidden-class.png
  src/_img/fast-properties/hole.png
  src/_img/hash-code/ares-6.png
  src/_img/high-performance-es2015/comparison.png
  src/_img/ignition-interpreter/ignition-pipeline.png
  src/_img/improved-code-caching/compile.png
  src/_img/improved-code-caching/parse.png
  src/_img/jank-busters/gc-concurrent-threads.png
  src/_img/javascript-code-coverage/block-coverage.png
  src/_img/javascript-code-coverage/function-vs-block.png
  src/_img/launching-ignition-and-turbofan/benchmark-scores.png
  src/_img/launching-ignition-and-turbofan/improvements-per-website.png
  src/_img/lazy-unlinking/ares6.png
  src/_img/lazy-unlinking/awfy-ares6.png
  src/_img/lazy-unlinking/awfy-octane.png
  src/_img/lazy-unlinking/v8-overview.png
  src/_img/optimizing-proxies/1.png
  src/_img/optimizing-proxies/2.png
  src/_img/optimizing-proxies/3.png
  src/_img/optimizing-proxies/4.png
  src/_img/optimizing-proxies/5.png
  src/_img/optimizing-proxies/6.png
  src/_img/optimizing-proxies/7.png
  src/_img/optimizing-proxies/8.png
  src/_img/optimizing-v8-memory/heap-memory-reduction.png
  src/_img/real-world-performance/evolution.png
  src/_img/real-world-performance/startup-distribution.png
  src/_img/test-the-future/58.png
  src/_img/test-the-future/59.png
  src/_img/tracing-js-dom/chrome-65.png
  src/_img/tracing-js-dom/chrome-66.png
  src/_img/turbofan-jit/example-graph.png
  src/_img/v8-release-57/async.png
  src/_img/v8-release-59/angrybots.png
  src/_img/v8-release-61/call-construct.png
  src/_img/v8-release-61/checking-prototype.png
  src/_img/v8-release-62/hashcode-lookups.png
  src/_img/v8-release-64/codespace-consumption.png
  src/_img/v8-release-64/weak-collection.png
  src/_img/v8-release-66/async-generator.png
  src/_img/v8-release-68/context-jsfunction-before.png
  src/_img/web-tooling-benchmark/chart.png
Labels: cla: yes

#23 Further losslessly optimize outline SVGs
  src/_img/v8-ignition-outline.svg
  src/_img/v8-orinoco-outline.svg
  src/_img/v8-outline.svg
  src/_img/v8-turbofan-outline.svg
Labels: cla: yes

#22 Fix typo
  src/blog/dataview.md
Labels: cla: yes

#29 Improve Torque manual, specifically callables section
  src/docs/torque.md
Labels: cla: yes

#30 Avoid weird paragraph spacing
  src/_css/main.css
Labels: cla: yes

#31 Fix fragment in flake-bisect.md
  src/docs/flake-bisect.md
Labels: cla: yes

#33 typo in torque.md
  src/docs/torque.md
Labels: cla: yes

#36 Further losslessly optimize `v8-liftoff-outline.svg`
  src/_img/v8-liftoff-outline.svg
Labels: cla: yes

#37 Change in the last paragraph mentioning "Octane"
  src/docs/profile.md
Labels: cla: yes, docs

#38 Fix typo
  src/blog/v8-release-70.md
Labels: blog, cla: yes

#39 Added links to bugs
  src/docs/gdb-jit.md
Labels: cla: yes, docs

#40 Update and merge d8-android.md to cross-compile-arm.md
  src/docs/cross-compile-arm.md
  src/docs/d8-android.md
  src/docs/index.md
Labels: cla: yes, docs

#42 Further improvements to Torque manual
  src/docs/torque.md
Labels: cla: yes

#46 Update linux-perf.md
  src/docs/linux-perf.md
Labels: cla: yes

#45 Format Torque code examples
  src/docs/torque.md
Labels: cla: yes

#44 Add links to embedded builtins blog post
  src/blog/v8-release-69.md
Labels: cla: yes

#47 Fix a typo relating to the period length.
  src/blog/math-random.md
Labels: blog, cla: yes

#49 [docs] Add documentation for zero-cost async stack traces.
  src/docs/stack-trace-api.md
Labels: cla: yes, docs

#48 Fix link
  src/docs/build-gn.md
Labels: cla: yes

#50 Add V8 v7.1 release notes
  src/blog/v8-release-71.md
Labels: cla: yes
