Repository v8/v8.dev, pull requests merged in 2019-10, with the labels that each got.

#253 blog: add Top-Level `await` explainer
  src/features/_top-level-await.md
Labels: cla: yes, language features

#255 Improving V8 regular expressions
  src/_img/avatars/patrick-thier.jpg
  src/_img/avatars/patrick-thier@2x.jpg
  src/_img/regexp-tier-up/results-memory.svg
  src/_img/regexp-tier-up/results-speed.svg
  src/blog/regexp-tier-up.md
Labels: blog, cla: yes

#256 Further optimize `react-cliff` SVGs
  src/_img/react-cliff/01-javascript-types.svg
  src/_img/react-cliff/02-primitives-objects.svg
  src/_img/react-cliff/03-primitives-objects-typeof.svg
  src/_img/react-cliff/04-smi-vs-heapnumber.svg
  src/_img/react-cliff/05-update-smi.svg
  src/_img/react-cliff/06-update-heapnumber.svg
  src/_img/react-cliff/07-heapnumbers.svg
  src/_img/react-cliff/08-garbage-heapnumbers.svg
  src/_img/react-cliff/09-mutableheapnumber.svg
  src/_img/react-cliff/10-update-mutableheapnumber.svg
  src/_img/react-cliff/11-mutableheapnumber-to-heapnumber.svg
  src/_img/react-cliff/12-smi-no-boxing.svg
  src/_img/react-cliff/13-shape.svg
  src/_img/react-cliff/14-shape-transition.svg
  src/_img/react-cliff/15-shape-deprecation.svg
  src/_img/react-cliff/16-split-shape.svg
  src/_img/react-cliff/17-shape-nonextensible.svg
  src/_img/react-cliff/18-repro-shape-setup.svg
  src/_img/react-cliff/19-orphaned-shape.svg
  src/_img/react-cliff/20-fibernode-shape.svg
  src/_img/react-cliff/21-orphan-islands.svg
  src/_img/react-cliff/22-fix.svg
  src/_img/react-cliff/23-fix-fibernode-shape-1.svg
  src/_img/react-cliff/24-fix-fibernode-shape-2.svg
Labels: blog, cla: yes

#254 Add dark mode, fixes #252
  .gitignore
  .html-minifier.json
  package.json
  src/_css/feature-support.css
  src/_css/img/moon.svg
  src/_css/img/sun.svg
  src/_css/main.css
  src/_includes/layouts/base.njk
  src/_js/legacy.js
  src/_js/main.mjs
  src/blog/cost-of-javascript-2019.md
  src/blog/v8-lite.md
  src/index.njk
  src/logo.md
Labels: cla: yes, meta

#257 Promise.allSettled is enabled by default in Firefox 71
  src/features/promise-combinators.md
Labels: cla: yes, language features

#259 Further optimize `regexp-tier-up` SVGs
  src/_img/regexp-tier-up/results-memory.svg
  src/_img/regexp-tier-up/results-speed.svg
Labels: blog, cla: yes

#261 Fixes to Top-level await blog post
  src/features/top-level-await.md
Labels: cla: yes, language features

#262 Further optimize `v8-release-78` SVGs
  src/_img/v8-release-78/memory-savings.svg
  src/_img/v8-release-78/script-streaming-0.svg
  src/_img/v8-release-78/script-streaming-1.svg
  src/_img/v8-release-78/script-streaming-2.svg
  src/_img/v8-release-78/script-streaming-3.svg
Labels: blog, cla: yes

#263 Further optimize SVGs
  src/_img/twitter.svg
  src/_img/v8-liftoff-outline.svg
  src/_img/v8-orinoco-outline.svg
  src/_img/v8-outline.svg
Labels: cla: yes, meta

#265 Update d8.md: drop "Debug8" claim
  src/docs/d8.md
Labels: cla: yes

#268 Replace all Turbofan by TurboFan
  src/blog/high-performance-es2015.md
  src/blog/liftoff.md
  src/blog/test-the-future.md
  src/blog/v8-release-59.md
Labels: blog, cla: yes

#267 Update Firefox logo
  package.json
Labels: cla: yes, language features, meta

#264 Add instructions to back-merge via gerrit
  src/docs/merge-patch.md
Labels: cla: yes, docs

#266 Dynamically re-render Twitter widget, fixes #260
  .babelrc
  .gitignore
  package.json
  src/_js/main.mjs
  src/index.njk
Labels: cla: yes, meta

#270 Re-remove comments from output
  .babelrc
Labels: cla: yes

#271 Switch from babel-minify to Terser
  .babelrc
  package.json
Labels: cla: yes, meta

#272 Fix Google Analytics
  src/_js/main.mjs
Labels: cla: yes, meta

#273 Lint only staged Markdown files
  package.json
Labels: cla: yes, meta

#276 Fix link to chromium glossary
  src/docs/version-numbers.md
Labels: cla: yes
