Repository v8/v8.dev, pull requests merged in 2019-12, with the labels that each got.

#294 Bump installed version of `<dark-mode-toggle>`
  package.json
  src/_css/main.css
Labels: cla: yes, meta

#296 Describe js-implicit parameters
  src/docs/torque.md
Labels: cla: yes

#299 Updated to reflect that torque produces .h files for the build
  src/_img/docs/torque/build-process.svg
  src/docs/torque.md
Labels: cla: yes

#300 Make PWA icons maskable
  src/.webmanifest
  src/_img/v8-192x192.png
  src/_img/v8-512x512.png
  src/_img/v8-icon-1024x1024.png
  src/_img/v8-icon-192x192.png
  src/_img/v8-icon-512x512.png
Labels: cla: yes, meta

#302 Add RegExp match indices feature explainer
  src/features/regexp-match-indices.md
Labels: cla: yes

#309 Make too long code wrap
  src/_css/main.css
Labels: cla: yes, meta

#308 Make page zoomable
  src/_css/main.css
Labels: cla: yes, meta

#306 Handle pre in .note width changes
  src/_css/main.css
Labels: cla: yes, meta

#303 Add V8 v8.0 blog post
  .eleventy.js
  package.json
  src/_img/v8-release-80/pointer-compression-chart.svg
  src/blog/v8-release-80.md
Labels: blog, cla: yes

#311 Update link to "Contributing to Chromium"
  src/docs/contribute.md
Labels: cla: yes, docs

#314 Really actually fix those tweets on firefox
  src/blog/v8-release-80.md
Labels: blog, cla: yes

#315 Torque enums
  src/docs/torque.md
Labels: cla: yes
