Repository v8/v8.dev, pull requests merged in 2019-01, with the labels that each got.

#109 fix explanatory code in hash-code.md
  src/blog/hash-code.md
Labels: blog, cla: yes

#107 Further losslessly optimize SVGs
  src/_img/v8-ignition-outline.svg
  src/_img/v8-ignition.svg
  src/_img/v8-liftoff.svg
  src/_img/v8-turbofan-outline.svg
  src/_img/v8-turbofan.svg
Labels: cla: yes, meta

#111 Update dimensions of YouTube embeds
  src/blog/10-years.md
  src/blog/free-garbage-collection.md
  src/blog/tracing-js-dom.md
Labels: blog, cla: yes, meta

#112 Make YouTube embeds responsive
  src/_css/main.css
  src/blog/10-years.md
  src/blog/blinkon-6.md
  src/blog/elements-kinds.md
  src/blog/fast-async.md
  src/blog/free-garbage-collection.md
  src/blog/ignition-interpreter.md
  src/blog/jank-busters.md
  src/blog/tracing-js-dom.md
Labels: cla: yes, meta

#114 Trash talk blog post
  src/_img/trash-talk/01.svg
  src/_img/trash-talk/02.svg
  src/_img/trash-talk/03.svg
  src/_img/trash-talk/04.svg
  src/_img/trash-talk/05.svg
  src/_img/trash-talk/06.svg
  src/_img/trash-talk/07.svg
  src/_img/trash-talk/08.svg
  src/_img/trash-talk/09.svg
  src/_img/trash-talk/10.svg
  src/blog/trash-talk.md
Labels: blog, cla: yes

#115 Remove stray apostrophe
  src/blog/trash-talk.md
Labels: blog, cla: yes

#120 Add pre-commit hook for linting
  package.json
Labels: cla: yes, meta

#122 document Torque's transient types
  src/docs/torque.md
Labels: cla: yes, docs

#123 Document Torque class types and %-style intrinsics
  src/docs/torque.md
Labels: cla: yes, docs

#124 Change Google Chrome to Chromium and derivatives
  src/docs/index.md
  src/index.njk
Labels: cla: yes, meta

#127 Further losslessly optimize SVGs
  src/_img/v8-liftoff-outline.svg
  src/_img/v8-liftoff.svg
  src/_img/v8-outline.svg
  src/_img/v8-turbofan-outline.svg
  src/_img/v8-turbofan.svg
  src/_img/v8.svg
Labels: cla: yes, meta

#125 Fix syntax highlighting in cross-compile-arm docs
  src/docs/cross-compile-arm.md
Labels: cla: yes, docs

#128 Further losslessly optimize SVGs
  src/_img/v8-liftoff-outline.svg
  src/_img/v8-liftoff.svg
Labels: cla: yes, meta

#129 Describe deferred blocks
  src/docs/torque.md
Labels: cla: yes

#130 Lightly describe tailcalls in the manual
  src/docs/torque.md
Labels: cla: yes

#132 Reverse list numbering of posts
  src/_includes/posts.njk
  src/index.njk
Labels: cla: yes, meta

#134 Remove broken Design Elements link
  src/docs/embed.md
Labels: cla: yes, docs

#135 Add comment on build dependency for node integration
  src/docs/node-integration.md
Labels: cla: yes

#137 Note that --async-stack-traces is on by default in V8 v.7.3
  src/blog/fast-async.md
Labels: blog, cla: yes

#138 Fix: Real value of JSON.stringify
  src/blog/v8-release-72.md
Labels: cla: yes
