Repository v8/v8.dev, pull requests merged in 2020-07, with the labels that each got.

#433 Add private methods and accessors to v8.4 release blog
  src/blog/v8-release-84.md
  src/features/class-fields.md
Labels: cla: yes

#436 Resolves #435
  src/blog/v8-release-84.md
Labels: cla: yes

#440 Update firebase tools and add regex redirects
  firebase.json
  package.json
Labels: cla: yes

#441 Remove recommendation to add No-Try
  src/docs/merge-patch.md
Labels: cla: yes

#442 Add AggregateError explanation
  src/features/promise-combinators.md
Labels: cla: yes, language features

#443 Add note on special replacement patterns w.r.t. replaceAll
  src/features/string-replaceall.md
Labels: cla: yes, language features

#446 Update feature support for logical assignment
  src/features/logical-assignment.md
Labels: cla: yes

#445 V8 v8.5 release blog post
  src/_img/avatars/zeynep-cankara.jpg
  src/_img/avatars/zeynep-cankara@2x.jpg
  src/blog/v8-release-85.md
Labels: cla: yes

#447 Fix typo in example code on 8.5 release post
  src/blog/v8-release-85.md
Labels: cla: yes

#448 Update Clemens' name (Hammacher -> Backes)
  src/_img/avatars/clemens-backes.jpg
  src/_img/avatars/clemens-backes@2x.jpg
  src/blog/liftoff.md
  src/blog/v8-release-73.md
Labels: blog, cla: yes

#444 Update @MayaLekova’s name
  src/blog/fast-async.md
  src/blog/lazy-unlinking.md
  src/blog/optimizing-proxies.md
  src/features/optional-chaining.md
  src/features/regexp-match-indices.md
Labels: blog, cla: yes

#450 Revert "Remove recommendation to add No-Try"
  src/docs/merge-patch.md
Labels: cla: yes

#449 Mention that Promise.any is on track to be included in ES2021
  src/features/promise-combinators.md
Labels: cla: yes, language features

#451 Fix minor nits
  src/blog/v8-release-85.md
Labels: blog, cla: yes

#452 Prefer inclusive language
  src/blog/bigint.md
  src/blog/heap-size-limit.md
  src/blog/modern-javascript.md
  src/blog/v8-nodejs.md
  src/blog/v8-release-50.md
  src/blog/v8-release-51.md
  src/docs/source-code.md
  src/docs/trace.md
Labels: cla: yes, meta

#454 Add page about respectful code
  src/docs/index.md
  src/docs/respectful-code.md
Labels: cla: yes
