Repository v8/v8.dev, pull requests merged in 2020-04, with the labels that each got.

#357 Fix instructions for `gm mjsunit/specific-test`
  src/docs/test.md
Labels: cla: yes

#336 Add blog post: Understanding ecmascript part 3
  src/blog/understanding-ecmascript-part-3.md
Labels: cla: yes

#358 Use language-grammar where possible
  src/blog/understanding-ecmascript-part-3.md
Labels: blog, cla: yes

#359 Fix typo
  src/blog/understanding-ecmascript-part-3.md
Labels: blog, cla: yes

#360 Correct statement about emojis
  src/blog/understanding-ecmascript-part-3.md
Labels: cla: yes

#364 Fix figure markup
  src/blog/pointer-compression.md
Labels: cla: yes

#337 Update merge-patch.md
  src/docs/merge-patch.md
Labels: cla: yes, docs

#366 Fix FormalParameters parameters
  src/blog/understanding-ecmascript-part-3.md
Labels: cla: yes

#367 Language fix
  src/blog/understanding-ecmascript-part-3.md
Labels: cla: yes

#365 Update debug-arm.md documentation.
  prism-languages.js
  src/docs/debug-arm.md
  src/docs/index.md
Labels: cla: yes

#369 Disallow inline images in a custom plugin
  md-embed-image.js
  src/blog/pointer-compression.md
  src/blog/v8-release-77.md
Labels: cla: yes, meta

#373 Define a `grammar` highlighter
  prism-languages.js
  src/_css/main.css
  src/blog/understanding-ecmascript-part-2.md
  src/blog/understanding-ecmascript-part-3.md
  src/docs/torque.md
Labels: blog, cla: yes, meta

#374 Revert "Add syntax highlighting support for numeric separators"
  prism-languages.js
Labels: cla: yes, meta

#375 Upgrade markdown-it-implicit-figures
  package.json
Labels: cla: yes, meta

#372 Update Safari support status for String#replaceAll
  src/features/nullish-coalescing.md
  src/features/string-replaceall.md
Labels: cla: yes, language features

#381 Update weak references explainer with new FinalizationRegistry API
  src/features/weak-references.md
Labels: cla: yes, language features

#383 Fix minor nits
  src/blog/pointer-compression.md
Labels: blog, cla: yes

#379 Fix typo in GN name: v8_untrusted_code_mitigations
  src/docs/untrusted-code-mitigations.md
Labels: cla: yes

#384 Update embed.md instructions for pointer compression
  src/docs/embed.md
Labels: cla: yes

#386 Point wasm_simd128.h to the LLVM repo
  src/features/simd.md
Labels: cla: yes

#385 Update Torque types documentation
  src/docs/torque.md
Labels: cla: yes

#388 Update feature support tables per Node.js v14
  src/features/intl-displaynames.md
  src/features/nullish-coalescing.md
  src/features/optional-chaining.md
Labels: cla: yes, language features

#389 Update wording in optional catch binding text
  src/features/optional-catch-binding.md
Labels: cla: yes

#387 wasm-decompile blog post
  src/_img/avatars/wouter-van-oortmerssen.jpg
  src/_img/avatars/wouter-van-oortmerssen@2x.jpg
  src/blog/wasm-decompile.md
Labels: blog, cla: yes

#392 Typo fix
  src/blog/understanding-ecmascript-part-1.md
Labels: cla: yes

#391 Optional chaining support available in Firefox 74
  src/features/optional-chaining.md
Labels: cla: yes
