Repository v8/v8.dev, pull requests merged in 2020-09, with the labels that each got.

#463 Enlarge link targets
  src/blog/v8-release-85.md
Labels: blog, cla: yes

#465 Remove unneeded routing rule (#464)
  firebase.json
Labels: cla: yes

#466 Reformat firebase.json
  firebase.json
Labels: cla: yes, meta

#467 Note that Safari 14 supports logical assignment
  src/features/logical-assignment.md
Labels: cla: yes, language features

#474 V8 release 8.6
  src/_img/v8-release-86/simd.svg
  src/blog/v8-release-86.md
Labels: blog, cla: yes

#477 Link to tweet
  src/blog/v8-release-86.md
Labels: blog, cla: yes

#475 Remove section on debugging SIMD in Liftoff
  src/blog/v8-release-86.md
Labels: cla: yes

#468 Add a feature explainer about Atomics
  src/features/atomics.md
Labels: cla: yes

#478 Code style nits
  src/features/atomics.md
Labels: blog, cla: yes

#472 Slack Tracking
  src/_img/avatars/michael-stanton.avif
  src/_img/avatars/michael-stanton.jpg
  src/_img/avatars/michael-stanton@2x.avif
  src/_img/avatars/michael-stanton@2x.jpg
  src/_img/slack-tracking/gc-heap-1.svg
  src/_img/slack-tracking/gc-heap-2.svg
  src/_img/slack-tracking/gc-heap-3.svg
  src/_img/slack-tracking/gc-heap-4.svg
  src/_img/slack-tracking/property-layout.svg
  src/_img/slack-tracking/root-map-1.svg
  src/_img/slack-tracking/root-map-2.svg
  src/_img/slack-tracking/root-map-3.svg
  src/blog/slack-tracking.md
  src/docs/index.md
Labels: cla: yes

#480 Fix typo in the method lock() in atomics.md
  src/features/atomics.md
Labels: cla: yes
