Repository v8/v8.dev, pull requests merged in 2020-08, with the labels that each got.

#457 Update information on using perf
  src/docs/linux-perf.md
Labels: cla: yes

#455 Preload dark mode toggle code
  src/_includes/layouts/base.njk
  src/_js/main.mjs
Labels: cla: yes

#458 Add tags to the Understanding ECMAScript posts
  src/blog/understanding-ecmascript-part-1.md
  src/blog/understanding-ecmascript-part-2.md
  src/blog/understanding-ecmascript-part-3.md
  src/blog/understanding-ecmascript-part-4.md
Labels: cla: yes

#459 Minor fixes in perf docs
  src/docs/linux-perf.md
Labels: cla: yes

#453 Add more redirects
  firebase.json
  src/docs/api.md
  src/docs/index.md
Labels: cla: yes

#437 Clarify expectations around finalizer callbacks
  src/features/weak-references.md
Labels: cla: yes, language features

#439 Add AIX, ppc64le and s390x as supported architectures
  src/docs/index.md
Labels: cla: yes

#461 Update Promise.any feature support
  src/features/promise-combinators.md
Labels: cla: yes, language features

#426 Update dark mode toggle
  package.json
Labels: cla: yes, meta
