Repository v8/v8.dev, pull requests merged in 2020-05, with the labels that each got.

#393 Add blog post: V8 release v8.3
  src/_img/avatars/victor-gomes.jpg
  src/_img/avatars/victor-gomes@2x.jpg
  src/blog/v8-release-83.md
Labels: blog, cla: yes

#397 Update feature support for String#replaceAll
  src/features/string-replaceall.md
Labels: cla: yes, language features

#398 Add bikineev's avatar
  src/_img/avatars/anton-bikineev.jpg
  src/_img/avatars/anton-bikineev@2x.jpg
Labels: cla: yes

#390 Add logical assignment feature explainer
  src/features/logical-assignment.md
Labels: cla: yes, language features

#403 Add omerkatz's avatar
  src/_img/avatars/omer-katz.jpg
  src/_img/avatars/omer-katz@2x.jpg
Labels: cla: yes

#400 Update feature support statuses for different proposals
  src/features/class-fields.md
  src/features/optional-chaining.md
  src/features/promise-combinators.md
  src/features/string-replaceall.md
  src/features/string-trimming.md
  src/features/weak-references.md
  src/features/well-formed-json-stringify.md
Labels: cla: yes

#401 Up to 4GB of memory in WebAssembly
  src/_img/avatars/jakob-kummerow.jpg
  src/_img/avatars/jakob-kummerow@2x.jpg
  src/blog/4gb-wasm-memory.md
Labels: cla: yes

#405 Add a comment about tags in the node-integration doc
  src/docs/node-integration.md
Labels: cla: yes

#406 Update String#replaceAll support to include Chrome 85
  src/features/string-replaceall.md
Labels: cla: yes, language features

#399 Add a blog post: Understanding the ECMAScript spec, part 4
  src/blog/understanding-ecmascript-part-4.md
Labels: cla: yes

#407 Fix typo in understanding-ecmascript-part-4.md
  src/blog/understanding-ecmascript-part-4.md
Labels: cla: yes

#409 Update @MayaLekova’s Twitter handle
  src/blog/fast-async.md
  src/blog/optimizing-proxies.md
  src/features/optional-chaining.md
  src/features/regexp-match-indices.md
Labels: cla: yes, meta

#408 Top-level await is partially supported in Chrome
  src/features/top-level-await.md
Labels: cla: yes

#404 Blog post: High-performance garbage collection for C++
  src/_img/high-performance-cpp-gc/concurrent-sweeping.svg
  src/_img/high-performance-cpp-gc/incremental-sweeping.svg
  src/_img/high-performance-cpp-gc/results.svg
  src/_img/high-performance-cpp-gc/stop-the-world-sweeping.svg
  src/blog/high-performance-cpp-gc.md
Labels: cla: yes

#411 Fix typo
  src/docs/merge-patch.md
Labels: cla: yes

#412 adding redirects
  firebase.json
Labels: cla: yes
