Repository v8/v8.dev, pull requests merged in 2020-06, with the labels that each got.

#310 Conditionally include PWACompat
  src/_js/main.mjs
Labels: cla: yes, meta

#415 Adding more redirects
  firebase.json
Labels: cla: yes, meta

#417 Add origin trial details to SIMD feature guide
  src/features/simd.md
Labels: cla: yes

#419 Update <dark-mode-toggle> version
  package.json
Labels: cla: yes, meta

#420 Add support for updated field
  src/_includes/layouts/feature.njk
  src/_includes/layouts/post.njk
  src/blog.atom.njk
  src/features.atom.njk
  src/sitemap.xml.njk
Labels: cla: yes, meta

#423 Add DevTools checklist to Wasm shipping checklist.
  src/docs/wasm-shipping-checklist.md
Labels: cla: yes, docs

#418 Update Code Caching for Devs post section on service worker cache.
  src/blog/code-caching-for-devs.md
Labels: cla: yes

#424 Adding redirect for tools
  firebase.json
Labels: cla: yes

#425 Update dependencies
  package.json
Labels: cla: yes, meta

#421 Update WeakRefs feature to match upcoming web.dev LIVE talk
  src/_img/weakrefs/after-start.svg
  src/_img/weakrefs/after-stop.svg
  src/_img/weakrefs/weak-after-gc.svg
  src/_img/weakrefs/weak-after-start.svg
  src/_img/weakrefs/weak-after-stop.svg
  src/features/weak-references.md
Labels: cla: yes, language features

#429 Add clarifying note about ||= and ??= for innerHTML
  src/features/logical-assignment.md
Labels: cla: yes

#427 Add note to add blink CQ bot when shipping wasm features
  src/docs/wasm-shipping-checklist.md
Labels: cla: yes

#428 Add redirect rule
  firebase.json
Labels: cla: yes

#432 Fix v8.3 release post
  src/blog/v8-release-83.md
Labels: cla: yes

#431 V8 v8.4 release blog post
  src/blog/v8-release-84.md
Labels: cla: yes
