Repository v8/v8.dev, pull requests merged in 2020-03, with the labels that each got.

#327 Add a blog post: Understanding the ECMAScript spec, part 2
  src/blog/understanding-ecmascript-part-2.md
Labels: blog, cla: yes

#338 Updated the async stack traces default info
  src/docs/stack-trace-api.md
Labels: blog, cla: yes

#341 Add authenticating with Google Storage step
  src/docs/build.md
Labels: cla: yes

#342 Add v8:: to all API calls
  src/docs/embed.md
Labels: cla: yes, docs

#343 Add Igor's avatar
  src/_img/avatars/igor-sheludko.jpg
  src/_img/avatars/igor-sheludko@2x.jpg
Labels: cla: yes

#345 Fix styling for wide content on Safari
  src/_css/main.css
Labels: cla: yes

#348 Link to the internal committer permissions process
  src/docs/become-committer.md
Labels: cla: yes

#347 Wasm staging checklist
  src/docs/index.md
  src/docs/wasm-shipping-checklist.md
Labels: cla: yes

#344 Pointer Compression blog post
  .eleventy.js
  .markdownlint.json
  package.json
  src/_css/main.css
  src/_img/pointer-compression/heap-layout-0.svg
  src/_img/pointer-compression/heap-layout-1.svg
  src/_img/pointer-compression/heap-layout-2.svg
  src/_img/pointer-compression/heap-point-1.svg
  src/_img/pointer-compression/heap-point-2.svg
  src/_img/pointer-compression/heap-point-3.svg
  src/_img/pointer-compression/memory-chrome.svg
  src/_img/pointer-compression/perf-octane-1.svg
  src/_img/pointer-compression/perf-octane-2.svg
  src/_img/pointer-compression/perf-octane-3.svg
  src/_img/pointer-compression/performance-improvements.svg
  src/_img/pointer-compression/v8-heap-memory.svg
  src/blog/pointer-compression.md
Labels: cla: yes

#351 Add missing figcaption to a blog post
  src/blog/understanding-ecmascript-part-1.md
Labels: cla: yes

#353 Headings Fix
  src/blog/pointer-compression.md
Labels: cla: yes

#355 Change alt to figcaption in Liftoff post
  src/blog/liftoff.md
Labels: blog, cla: yes

#356 Convert few more images with attributes
  src/blog/code-caching-for-devs.md
  src/blog/cost-of-javascript-2019.md
  src/blog/v8-lite.md
Labels: blog, cla: yes
