Repository v8/v8.dev, pull requests merged in 2021-05, with the labels that each got.

#548 V8 release v9.1
  src/blog/v8-release-91.md
Labels: cla: yes

#549 Update iOS cross-compile instructions
  src/docs/cross-compile-ios.md
Labels: cla: yes

#551 Add blog post on short builtin calls
  src/_img/short-builtin-calls/benchmarks.svg
  src/_img/short-builtin-calls/v8-browsing.svg
  src/blog/short-builtin-calls.md
Labels: cla: yes

#552 Update SIMD again
  src/features/simd.md
Labels: cla: yes

#554 Update async stack trace documentation
  src/docs/stack-trace-api.md
Labels: cla: yes, docs

#553 Add Sparkplug blog post
  .eleventy.js
  md-embed-image.js
  src/_css/main.css
  src/_img/sparkplug/benchmark-browsing-linux-perf.svg
  src/_img/sparkplug/benchmark-browsing-mac-10_12_laptop_low_end-perf.svg
  src/_img/sparkplug/benchmark-browsing-mac-10_13_laptop_high_end-perf.svg
  src/_img/sparkplug/benchmark-browsing-mac-m1_mini_2020-perf.svg
  src/_img/sparkplug/benchmark-browsing-win-10-perf.svg
  src/_img/sparkplug/benchmark-speedometer.svg
  src/_includes/layouts/base.njk
  src/_svg/sparkplug/basic-frame.svg
  src/_svg/sparkplug/interpreter-frame.svg
  src/_svg/sparkplug/js-frame.svg
  src/_svg/sparkplug/machine-frame.svg
  src/_svg/sparkplug/pipeline.svg
  src/_svg/sparkplug/sparkplug-frame.svg
  src/blog/sparkplug.md
Labels: cla: yes

#555 Correct “TurboFan” casing
  src/_svg/sparkplug/pipeline.svg
Labels: blog, cla: yes

#557 Minify inline <style> and <script>
  .html-minifier.json
  package.json
Labels: cla: yes
