Repository v8/v8.dev, pull requests merged in 2021-01, with the labels that each got.

#519 Clarify recommended BigInt() usage
  src/features/bigint.md
Labels: cla: yes, language features

#508 New post: An additional non-backtracking RegExp engine
  src/_img/non-backtracking-regexp/example-automaton.svg
  src/_img/non-backtracking-regexp/runtime-plot.svg
  src/_img/non-backtracking-regexp/state-types.svg
  src/blog/non-backtracking-regexp.md
Labels: cla: yes

#518 Fix typo in array-sort.md
  src/blog/array-sort.md
Labels: cla: yes

#494 Update dead link to CPU profiler docs
  src/docs/profile.md
Labels: cla: yes

#497 update: cq link in source-code.md
  src/docs/source-code.md
Labels: cla: yes

#506 Remove AVIF MIME type special-casing
  firebase.json
Labels: cla: yes, do not merge

#509 Remove extra slash in node integration doc
  src/docs/node-integration.md
Labels: cla: yes

#490 Further optimize SVGs in `src/_css/img`
  src/_css/img/babel.svg
  src/_css/img/moon.svg
  src/_css/img/nodejs.svg
  src/_css/img/sun.svg
Labels: cla: yes

#515 Fix typos
  src/docs/benchmarks.md
  src/docs/profile-chromium.md
  src/docs/torque.md
  src/features/object-fromentries.md
Labels: cla: yes

#517 chore: Intl.RelativeTimeFormat added in Safari 14
  src/features/intl-relativetimeformat.md
Labels: cla: yes
